services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    networks: 
      - mongo-compose-network
    environment:
      - MONGO_INIT_ROOT_USERNAME=root
      - MONGO_INIT_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks: 
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongo_db
volumes:
  mongo: {}
networks:
  mongo-compose-network:
    driver: bridge
